language: ruby
rvm:
  - 2.1
  - 2.2.5
  - 2.3.1

sudo: false

script:
  - script/cibuild

cache:
  - bundler
  - apt

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

git:
  depth: 10

matrix:
  exclude:
    -
      os: osx
      rvm: 2.2.5 # broken on Travis ðŸ™„
    -
      os: osx
      rvm: 2.3.1 # broken on Travis ðŸ™„

addons:
  apt:
    packages:
    - cmake
    - bison
    - flex
    - libffi-dev
    - libxml2-dev
    - libgdk-pixbuf2.0-dev
    - libcairo2-dev
    - libpango1.0-dev
    - ttf-lyx

install:
  - echo $TRAVIS_OS_NAME
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update      ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install glib; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install gdk-pixbuf; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install cairo; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install pango; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew link gettext --force; fi
  - bundle install
